config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'blogs#index'
  resources :blogs do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5}
  validates :text, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for(resource)
    "/"
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @blogs = Blog.all.order("created_at DESC")
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    unless @blog.save then
      flash.now[:notice] = "投稿に失敗しました"
      render action: :new
    end 
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    unless @blog.update(blog_params) then
      flash.now[:notice] = "更新に失敗しました"
      render action: :new
    end 
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blog = Blog.find(params[:id])
    @comment = @blog.comments.build(comment_params)
    render :index if @comment.save
  end

  private
  def comment_params
    params.require(:comment).permit(:text)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_blogs.html.erb
<% @blogs.each do |blog| %>
  <div class="row">
    <div class="col s9">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <p>【タイトル】</p>
            <%= blog.title %>
          <p>【内容】</p>
            <%= blog.text %>
        </div>
        <div class="card-action">
          <%= link_to "詳細", blog_path(blog.id), method: :get %>
          <%= link_to "編集", edit_blog_path(blog.id), method: :get %>
          <%= link_to "削除", blog_path(blog.id), method: :delete, data: {confirm: '削除してもよろしいですか?'} %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/blogs/_form.html.erb
<div class = "container">
  <div class = "row" >
    <%= form_for @blog do |f| %>
      <% if flash.now[:notice] %>
        <p><%= flash.now[:notice] %></p>
      <% end %>
    <div class = "container">
      <div class = "cols9" >
        <p>
          <%= f.label :title, "タイトル" %><br>
          <%= f.text_field :title %>
        </p>
      </div>
    </div>
      
    <div class = "container">
      <div class = "cols9">
        <div class = "h-30">
          <p>
            <%= f.label :text, "内容" %><br>
            <%= f.text_area :text %>
          </p>
        </div>
      </div>
    </div>

    <div class = "container">
      <div class = "cols9" >
        <p>
          <%= f.submit "送信" %>
        </p>
        <%= link_to '戻る', "/" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/blogs/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/blogs/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class = "container">
  <div class = "cols9">
    <h1>ブログを更新</h1>
  </div>
</div>
<%= render 'form' %>

app/views/blogs/index.html.erb
<nav class = "light-blue lighten-4">
  <div class="nav-wrapper">
    <a href="/" class="brand-logo center">MyBlog</a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <% if user_signed_in? %>
          <li class = "#37474f blue-grey darken-3">
            <%= link_to "ログアウト", "/users/sign_out", method: :delete, data: {confirm: 'ログアウトしてもよろしいですか?'} %>
          </li>
          <li class = "#37474f blue-grey darken-3">
            <%= link_to "投稿", "/blogs/new", method: :get %>
          </li>
        <% else %>
          <li class = "#37474f blue-grey darken-3">
            <%= link_to "ログイン", "/users/sign_in", method: :post %>
          </li>
          <li class = "#37474f blue-grey darken-3">
            <%= link_to "新規登録", "/users/sign_up", method: :get %>
          </li>
        <% end %>
      </ul>
  </div>
</nav>

<div class = "contents row">
  <h1>ブログ投稿一覧</h1>
  <%= render 'blogs' %>
</div>

<footer class="page-footer">
  <div class= "light-blue lighten-4">
    <div class = "container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Footer Content</h5>
          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
            </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        © 2014 Copyright Text
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </div>
</footer>

app/views/blogs/new.html.erb
<div class = "container">
  <div class = "cols9">
    <h1>ブログを投稿</h1>
  </div>
</div>
<%= render 'form' %>

app/views/blogs/show.html.erb
<div class = "container">
  <div class = "cols9">
    <h1>ブログの詳細</h1>
  </div>
</div>
<div class="row">
  <div class="col s9">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <p>
          <strong>タイトル：</strong>
          <%= @blog.title %>
        </p>
        <p>
          <strong>内容：</strong>
          <%= @blog.text %>
        </p>
        <div class="card-action">
          <%= link_to "編集", edit_blog_path(@blog.id), method: :get %>
          <%= link_to "削除", blog_path(@blog.id), method: :delete, data: {confirm: '削除してもよろしいですか?'} %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class = "container">
  <div class = "row" >
    <div class = "col s6">
      <%= form_with(model: @user, local: true) do |f| %>
        <p>
          <%= f.label :text, "コメント" %><br>
          <%= f.text_area :text %>
        </p>
        <p>
          <%= f.submit "コメントする" %>
        </p>
        <%= link_to '戻る', "/" %>
      <% end %>
    </div>
  </div>
</div>

<div class="comments">   
  <h4>＜コメント一覧＞</h4>
</div>

app/views/blogs/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogsApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>